---
title: "Asymptotic null distributions of the uniformity tests in the `sphunif` package"
author: "Eduardo García-Portugués"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: yes
    fig_width: 7
    fig_height: 7
vignette: >
  %\VignetteIndexEntry{Asymptotic null distributions of the uniformity tests in the `sphunif` package}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%",
  fig.asp = 0.5,
  eval = FALSE
)
```

## Checking function

The function `check_asymp_distr` evaluates empirically that the implemented null asymptotic distributions of the uniformity statistics are coherent with the finite sample distributions (obtained by Monte Carlo).

```{r, check-fun}
# Load package
library(sphunif)

# Check function
check_asymp_distr <- function(samp, stat, ...) {

  # Optional arguments for the test statistic and distribution
  dots <- list(...)
  names_dots <- names(dots)

  # Is samp a Psi matrix?
  if (("Psi_in_X" %in% names_dots) && dots$Psi_in_X) {

    if (is.null(dots$p)) {

      stop("p must be provided if Psi_in_X = TRUE")

    } else {

      p <- dots$p

    }
    name <- "sph_stat_"
    M <- ncol(samp)
    l <- 3

  # Get the data dimension from samp
  } else {

    d <- dim(samp)
    l <- length(d)
    if (l == 3) {

      p <- d[2]
      name <- "sph_stat_"
      M <- d[3]

    } else {

      p <- 2
      name <- "cir_stat_"
      M <- d[2]

    }

    # The dimension is used by some statistics and distributions
    dots$p <- p
    names_dots <- names(dots)

  }

  # Separate arguments for statistic and distribution
  stat_args <- dots[names_dots %in% names(formals(paste0(name, stat)))]
  distr_args <- dots[names_dots %in% names(formals(paste0("d_", name, stat)))]
  main_arg <- list(samp)
  names(main_arg) <- ifelse(l == 3, "X", "Theta")
  stats <- drop(do.call(what = paste0(name, stat),
                        args = c(main_arg, stat_args)))

  # KS test
  if (stat == "Hodges_Ajne") {

    x_eval <- (n %/% 2 + 1):ceiling(0.75 * n)
    y_eval <- do.call(what = paste0("p_", name, stat),
                      args = c(list(x = x_eval), distr_args))
    KS <- dgof::ks.test(x = stats, y = stepfun(x = x_eval, y = c(0, y_eval)))

  } else if (stat == "Num_uncover") {

    x_eval <- (n %/% 2 + 1):ceiling(0.75 * n)
    y_eval <- do.call(what = paste0("p_", name, stat),
                      args = c(list(x = x_eval), distr_args))
    KS <- dgof::ks.test(x = stats, y = stepfun(x = x_eval, y = c(0, y_eval)))

  } else {

    f <- function(...) ks.test(x = stats, y = paste0("p_", name, stat), ...)
    KS <- do.call(what = f, args = distr_args)

  }

  # Two plots
  par(mfrow = c(1, 2), mar = c(4, 4, 2, 1) + 0.1)

  # Histogram vs density plot
  breaks <- switch((stat %in% c("Hodges_Ajne", "Num_uncover")) + 1,
                   ceiling(sqrt(M)), x_eval - 0.5)
  hist(stats, freq = FALSE, breaks = breaks,
       main = paste("Histogram of", stat, "statistic"), xlab = "Statistics",
       col = rgb(1, 1, 1, alpha = 0.5), cex.main = 0.75, cex.lab = 0.75)
  rug(stats)

  # Add lines
  if (stat == "Hodges_Ajne") {

    lines(x_eval, do.call(what = "d_cir_stat_Hodges_Ajne",
                          args = c(list(x = cbind(x_eval)), distr_args)),
          type = "h", col = 2)

  } else if (stat == "Num_uncover") {

    lines(x_eval, do.call(what = "d_cir_stat_Num_uncover",
                          args = c(list(x = cbind(x_eval)), distr_args)),
          type = "h", col = 2)

  } else {

    curve(do.call(what = paste0("d_", name, stat),
                  args = c(list(x = cbind(x)), distr_args)),
          n = 100, add = TRUE, col = 2)

  }

  # PP plot
  plot(ecdf(stats)(stats), do.call(what = paste0("p_", name, stat),
                                   args = c(list(x = stats), distr_args)),
       main = paste0("PP-plot of ", stat, ", K-S p-value = ",
                     sprintf("%.4f", KS$p.value)),
       xlab = "Empirical probability", ylab = "Theoretical probability",
       cex = 0.1, cex.main = 0.75, cex.lab = 0.75)
  abline(a = 0, b = 1, col = 2)

  # Return KS test
  return(KS)

}

# Sample size
n <- 100

# Monte Carlo replicates
M <- 200

# Seed
seed <- 987654321
```

## Circular ($p = 2$) statistics

```{r, check-cir}
# Sample
set.seed(seed)
samp_cir <- r_unif_cir(n = n, M = M, sorted = TRUE)
print(object.size(samp_cir), units = "MiB")

# Ajne
check_asymp_distr(samp = samp_cir, stat = "Ajne")

# Bakshaev
check_asymp_distr(samp = samp_cir, stat = "Bakshaev")

# Bingham
check_asymp_distr(samp = samp_cir, stat = "Bingham")

# Cressie: unimplemented asymptotic distribution

# Cuesta_Albertos: unknown asymptotic distribution

# Feltz_Goldin: unknown asymptotic distribution

# Gine_Fn
check_asymp_distr(samp = samp_cir, stat = "Gine_Fn")

# Gine_Gn
check_asymp_distr(samp = samp_cir, stat = "Gine_Gn")

# Gini
check_asymp_distr(samp = samp_cir, stat = "Gini", sorted = TRUE)

# Gini_squared
check_asymp_distr(samp = samp_cir, stat = "Gini_squared", sorted = TRUE)

# Greenwood
check_asymp_distr(samp = samp_cir, stat = "Greenwood", sorted = TRUE)

# Hermans_Rasson
check_asymp_distr(samp = samp_cir, stat = "Hermans_Rasson")

# Hodges_Ajne
check_asymp_distr(samp = samp_cir, stat = "Hodges_Ajne", sorted = TRUE, n = n,
                  asymp_std = FALSE, exact = TRUE)

# Kuiper
check_asymp_distr(samp = samp_cir, stat = "Kuiper", n = n, sorted = TRUE)

# Log_gaps
check_asymp_distr(samp = samp_cir, stat = "Log_gaps", sorted = TRUE)

# Max_uncover
check_asymp_distr(samp = samp_cir, stat = "Max_uncover", sorted = TRUE)

# Num_uncover: TODO[add asymp_std]
# check_asymp_distr(samp = samp_cir, stat = "Num_uncover", sorted = TRUE,
#                   asymp_std = FALSE)

# PAD
check_asymp_distr(samp = samp_cir, stat = "PAD")

# PCvM
check_asymp_distr(samp = samp_cir, stat = "PCvM")

# PRt
check_asymp_distr(samp = samp_cir, stat = "PRt")

# Pycke
check_asymp_distr(samp = samp_cir, stat = "Pycke")

# Pycke_q
check_asymp_distr(samp = samp_cir, stat = "Pycke_q")

# Range
check_asymp_distr(samp = samp_cir, stat = "Range", n = n, sorted = TRUE,
                 gaps = FALSE)

# Rao
check_asymp_distr(samp = samp_cir, stat = "Rao", sorted = TRUE)

# Rayleigh
check_asymp_distr(samp = samp_cir, stat = "Rayleigh")

# Rothman
check_asymp_distr(samp = samp_cir, stat = "Rothman")

# Vacancy
check_asymp_distr(samp = samp_cir, stat = "Vacancy", sorted = TRUE)

# Watson
check_asymp_distr(samp = samp_cir, stat = "Watson", sorted = TRUE)

# Watson_1976 M^+
check_asymp_distr(samp = samp_cir, stat = "Watson_1976", sorted = TRUE,
                  minus = FALSE)

# Watson_1976 M^-
check_asymp_distr(samp = samp_cir, stat = "Watson_1976", sorted = TRUE,
                  minus = TRUE)
```

## Spherical ($p \ge 3$) statistics

### $p = 3$

```{r, check-sph-1}
# Sample
p <- 3
set.seed(seed)
samp_sph <- r_unif_sph(n = n, p = p, M = M)
Psi_samp_sph <- Psi_mat(data = samp_sph)
dim(Psi_samp_sph) <- c(dim(Psi_samp_sph), 1)
print(object.size(samp_sph), units = "MiB")
print(object.size(Psi_samp_sph), units = "MiB")

# Ajne
check_asymp_distr(samp = Psi_samp_sph, stat = "Ajne", p = p, Psi_in_X = TRUE)

# Bakshaev
check_asymp_distr(samp = Psi_samp_sph, stat = "Bakshaev", p = p,
                  Psi_in_X = TRUE)

# Bingham
check_asymp_distr(samp = samp_sph, stat = "Bingham")

# # Cai TODO[check statistic and asymptotic distribution]
# check_asymp_distr(samp = Psi_samp_sph, stat = "Cai", p = p, M = M,
#                   Psi_in_X = TRUE)

# Cuesta_Albertos: unknown asymptotic distribution

# Gine_Fn
check_asymp_distr(samp = Psi_samp_sph, stat = "Gine_Fn", p = p, Psi_in_X = TRUE)

# Gine_Gn
check_asymp_distr(samp = Psi_samp_sph, stat = "Gine_Gn", p = p, Psi_in_X = TRUE)

# PAD
check_asymp_distr(samp = Psi_samp_sph, stat = "PAD", p = p, Psi_in_X = TRUE)

# PCvM
check_asymp_distr(samp = Psi_samp_sph, stat = "PCvM", p = p, Psi_in_X = TRUE)

# PRt
check_asymp_distr(samp = Psi_samp_sph, stat = "PRt", p = p, Psi_in_X = TRUE)

# Pycke: unimplemented/unknown asymptotic distribution

# Rayleigh
check_asymp_distr(samp = samp_sph, stat = "Rayleigh")

# # Rayleigh_HD TODO[check statistic and asymptotic distribution]
# check_asymp_distr(samp = samp_sph, stat = "Rayleigh_HD", M = M)
```

### $p = 4$

```{r, check-sph-2}
# Sample
p <- 4
set.seed(seed)
samp_sph <- r_unif_sph(n = n, p = p, M = M)
Psi_samp_sph <- Psi_mat(data = samp_sph)
dim(Psi_samp_sph) <- c(dim(Psi_samp_sph), 1)
print(object.size(samp_sph), units = "MiB")
print(object.size(Psi_samp_sph), units = "MiB")

# Ajne
check_asymp_distr(samp = Psi_samp_sph, stat = "Ajne", p = p, Psi_in_X = TRUE)

# Bakshaev
check_asymp_distr(samp = Psi_samp_sph, stat = "Bakshaev", p = p,
                  Psi_in_X = TRUE)

# Bingham
check_asymp_distr(samp = samp_sph, stat = "Bingham")

# # Cai TODO[check statistic and asymptotic distribution]
# check_asymp_distr(samp = Psi_samp_sph, stat = "Cai", p = p, M = M,
#                   Psi_in_X = TRUE)

# Cuesta_Albertos: unknown asymptotic distribution

# Gine_Fn
check_asymp_distr(samp = Psi_samp_sph, stat = "Gine_Fn", p = p, Psi_in_X = TRUE)

# Gine_Gn
check_asymp_distr(samp = Psi_samp_sph, stat = "Gine_Gn", p = p, Psi_in_X = TRUE)

# PAD
check_asymp_distr(samp = Psi_samp_sph, stat = "PAD", p = p, Psi_in_X = TRUE)

# PCvM
check_asymp_distr(samp = Psi_samp_sph, stat = "PCvM", p = p, Psi_in_X = TRUE)

# PRt
check_asymp_distr(samp = Psi_samp_sph, stat = "PRt", p = p, Psi_in_X = TRUE)

# Pycke: unimplemented/unknown asymptotic distribution

# Rayleigh
check_asymp_distr(samp = samp_sph, stat = "Rayleigh")

# # Rayleigh_HD TODO[check statistic and asymptotic distribution]
# check_asymp_distr(samp = samp_sph, stat = "Rayleigh_HD", M = M)
```

### $p = 11$

```{r, check-sph-3}
# Sample
p <- 11
set.seed(seed)
samp_sph <- r_unif_sph(n = n, p = p, M = M)
Psi_samp_sph <- Psi_mat(data = samp_sph)
dim(Psi_samp_sph) <- c(dim(Psi_samp_sph), 1)
print(object.size(samp_sph), units = "MiB")
print(object.size(Psi_samp_sph), units = "MiB")

# Ajne
check_asymp_distr(samp = Psi_samp_sph, stat = "Ajne", p = p, Psi_in_X = TRUE)

# Bakshaev
check_asymp_distr(samp = Psi_samp_sph, stat = "Bakshaev", p = p,
                  Psi_in_X = TRUE)

# Bingham
check_asymp_distr(samp = samp_sph, stat = "Bingham")

# # Cai TODO[check statistic and asymptotic distribution]
# check_asymp_distr(samp = Psi_samp_sph, stat = "Cai", p = p, M = M,
#                   Psi_in_X = TRUE)

# Cuesta_Albertos: unknown asymptotic distribution

# Gine_Fn
check_asymp_distr(samp = Psi_samp_sph, stat = "Gine_Fn", p = p, Psi_in_X = TRUE)

# Gine_Gn
check_asymp_distr(samp = Psi_samp_sph, stat = "Gine_Gn", p = p, Psi_in_X = TRUE)

# PAD
check_asymp_distr(samp = Psi_samp_sph, stat = "PAD", p = p, Psi_in_X = TRUE)

# PCvM
check_asymp_distr(samp = Psi_samp_sph, stat = "PCvM", p = p, Psi_in_X = TRUE)

# PRt
check_asymp_distr(samp = Psi_samp_sph, stat = "PRt", p = p, Psi_in_X = TRUE)

# Pycke: unimplemented/unknown asymptotic distribution

# Rayleigh
check_asymp_distr(samp = samp_sph, stat = "Rayleigh")

# # Rayleigh_HD TODO[check statistic and asymptotic distribution]
# check_asymp_distr(samp = samp_sph, stat = "Rayleigh_HD", M = M)
```
